module ConfigRbsGenerator
  VERSION: String

  def self.run: () -> String

  class Outputs
    @text: String

    attr_reader text: ::String

    def initialize: () -> void
    def add_method_definition: ([::Symbol, (::String | ::Integer | ::Array[::String | ::Integer])] setting) -> ::String
    def finalize: -> ::String
  end
end
